version: '3'

services:

  myapp-mysql:
    build:
      context: ./MySQLDB/
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    networks:
      - spring-boot-mysql-network

  myapp-main:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - spring-boot-mysql-network
    depends_on:
      - myapp-mysql
    ports:
      - 8085:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_NAME=web_customer_tracker
      - DATABASE_PORT=3306
networks:
       spring-boot-mysql-network:
         driver: bridge   